In [ ]:
import os

print(os.listdir())

['.config', 'sample_data']

In [ ]:
import pandas as pd

df = pd.read_csv("Global COVID-19 Dataset.csv", encoding="latin1")

df.head()
df.shape
df.columns
df.info()
df.isnull().sum()

FileNotFoundError: [Errno 2] No such file or directory: 'Global COVID-19 Dataset.csv.xls'

In [ ]:
import os

os.listdir('/content/drive/MyDrive')

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:
df[df.isnull().any(axis=1)]

     S. No. Country Name  Cases  Deaths  Recovered
230     NaN          NaN    NaN     NaN        NaN
231     NaN          NaN    NaN     NaN        NaN
232     NaN          NaN    NaN     NaN        NaN
233     NaN          NaN    NaN     NaN        NaN
234     NaN          NaN    NaN     NaN        NaN
235     NaN          NaN    NaN     NaN        NaN
236     NaN          NaN    NaN     NaN        NaN
237     NaN          NaN    NaN     NaN        NaN

In [ ]:
print(df.shape)
print(df.isnull().sum())

(238, 5)
S. No.          8
Country Name    8
Cases           8
Deaths          8
Recovered       8
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(7)

In [ ]:
df.dtypes

S. No.          float64
Country Name     object
Cases           float64
Deaths          float64
Recovered       float64
dtype: object

In [ ]:
df.head(10)
df.tail()
print(df.columns.tolist())

['S. No.', 'Country Name', 'Cases', 'Deaths', 'Recovered']

In [ ]:
df[df["Cases"].isnull()]
df[["Cases","Deaths","Recovered"]].lt(0).sum()

Cases        0
Deaths       0
Recovered    0
dtype: int64

In [ ]:
df[df["Deaths"]+df["Recovered"]>df[ "Cases"]]
df.dtypes
df[["Cases","Deaths","Recovered"]].head()

       Cases    Deaths  Recovered
0  4524748.0  220831.0  4303917.0
1  1329266.0   38700.0  1290566.0
2   403638.0   16388.0   387250.0
3  2230381.0   49051.0  2181330.0
4   350589.0    9977.0   340612.0

In [ ]:
df[["Cases","Deaths","Recovered"]].apply(lambda x: x%1!=0).sum()

Cases        8
Deaths       8
Recovered    8
dtype: int64

In [ ]:
# Option 1: Convert to pandas nullable integer type which supports NaN values
df[["Cases", "Deaths", "Recovered"]] = df[["Cases", "Deaths", "Recovered"]].astype("Int64")

In [ ]:
df.dtypes
df["S. No."].isnull().sum()
df["S. No."] = df["S. No."].astype(int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
df.dtypes

S. No.          float64
Country Name     object
Cases             Int64
Deaths            Int64
Recovered         Int64
dtype: object

In [ ]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   S. No.        230 non-null    float64
 1   Country Name  230 non-null    object
 2   Cases         230 non-null    Int64
 3   Deaths        230 non-null    Int64
 4   Recovered     230 non-null    Int64
dtypes: Int64(3), float64(1), object(1)
memory usage: 10.1+ KB

In [ ]:
df.to_csv("cleaned_covid_data.csv", index=False)

In [ ]:
import os
os.listdir()

['.config',
 'drive',
 'Global COVID-19 Dataset.csv',
 'cleaned_covid_data.csv',
 'sample_data']

In [ ]:
import os

os.listdir('/content/drive/MyDrive')

['Colab Notebooks',
 'certificate (1).pdf',
 'certificate.pdf',
 '17551647028898163834884278584063.jpg',
 'Classroom',
 'PDFReader_Convert_20250912_233321_1.jpg',
 'isss sare answer ko detalied me batao (1).gsheet',
 'isss sare answer ko detalied me batao.gsheet',
 'Unit-2 Set-2 Multithreading.gdoc',
 'aktu result sem 1 ,2 and 3.pdf',
 'CV_2026070623524233.pdf',
 'My Resume.docx',
 'Document from khushi (2).pdf',
 'Document from khushi (1).pdf',
 'Document from khushi.pdf',
 'Screenshot_20260723-130015_Gmail.png',
 'Screenshot_20260723-171852_Gmail.png',
 'DAA_Assignment1_BCS503.docx',
 'photo (1) (1).jpeg',
 'photo (1).jpeg',
 'Ds - 3A -1',
 'Screenshot 2026-09-04 121124.png',
 'Screenshot 2026-09-05 125541.png',
 'Screenshot 2026-09-05 125711.png']

In [ ]:
pd.read_csv("cleaned_covid_data.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'cleaned_covid_data.csv'

In [ ]:
import os
os.listdir()

['.config', 'Global COVID-19 Dataset.csv.xls', 'sample_data']